### ISSUE TITLE
promethion ready - checklist

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/nanoporeReads_dataTransfer#142]
Todo's to make the workflow 'promethion ready'. Related to #138, #139, #140 

- [x] merge basecalled bam files (e.g. basecalled output)
- [x] fetch exact dorado (server) version + model used in MinKNOW and store this in the config / metadata to ship to end user. For MinKNOW v 23.07.12 the information in the json is confusing (e.g. guppy flags while dorado is used), the info in html should be correct. 
- [x] basecalled bam files generated with minKNOW are not compatible with dorado align (v0.4.1 & 0.5.0).
- [x] basecalled bam files generated with minKNOW are not compatible with modbam2bed.
- [x] model_def & model are confusing in the metadata yaml (HAC vs SUP)

**Comment by WardDeb** [comment]
per on site meeting:
- [ ] parameters should be parsed from sequencingrun.html files rather then json/md
- [ ] important to discriminate between minKNOW version/models & dorado models
- [ ] bam header information should be parsed for consistency

**Comment by caballero** [comment]
> merge basecalled bam files (e.g. basecalled output)
Implemented
> fetch exact dorado (server) version + model used in MinKNOW and store this in the config / metadata to ship to end user. For MinKNOW v 23.07.12 the information in the json is confusing (e.g. guppy flags while dorado is used), the info in html should be correct.
Correct version is captured from html and json reports, added software versions of the other programs too
> basecalled bam files generated with minKNOW are not compatible with dorado align (v0.4.1 & 0.5.0).
As basecalling and alignment is done in MinKNOW, this is not required
> basecalled bam files generated with minKNOW are not compatible with modbam2bed.
Changed modbam2bed with modkit
> model_def & model are confusing in the metadata yaml (HAC vs SUP)
Model is parsed from JSON, not need to run this separately
> parameters should be parsed from sequencingrun.html files rather then json/md
Implemented, but most parameters are defined in the json
> important to discriminate between minKNOW version/models & dorado models
We are capturing all versions reported
> bam header information should be parsed for consistency
This was not implemented as bam header can contain or not the model (i.e. CL:dorado basecaller hac,m6A ...)
> explore expansion on epi2me's basecalling workflow for implementation into minKNOW
todo
