### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by LeilyR** [maxplanck-ie/nanoporeReads_dataTransfer#18]
- [x] send email when fails or succeed  
- [x] change permission
- [x] copy to qc folder of deepseq
- [x] check GPU status before guppy submission
- [x] update std/hac/super model rules for different flowcell/kit modalities

Wontfix:
- [ ] mv to rapidus  (obsolete by longus seq_data volumes)
- [ ] map to transcript (downstream analysis will be limited to do data footprints).
- [x] add samtools flagstat (see mapping)
- [ ] bampycoQC optional, conditional to flagstat result (see mapping)

**Comment by WardDeb** [comment]
Additional ideas:

 - [ ] copy qc into a 'bioinfo' dir
 - [ ] populate email with relevant stats

**Comment by WardDeb** [comment]
the GPU status should become priority. Core dumps after a full round of basecalling are quite a big time waste.

**Comment by thomasmanke** [comment]
Unclear what is meant by "change permission" - please clarify.

**Comment by WardDeb** [comment]
I think the change permission would be something similar to what we do in dissect:
generate as chmod 700, open up to 740/750 on release
